name = "apt-enjin theme"
parent = "semantic-enjin"
license = "Apache 2.0"
licenselink = "https://go-enjin.org/license"
description = "The apt-enjin theme."
homepage = "https://go-enjin.org/"

[author]
    name = "The Go-Enjin Team"
    homepage = "https://go-enjin.org/"

[semantic.site]
    menu.mobile.style = "side"
    menu.desktop.style = "menu"
    page.font-stylesheets = [
        "https://fonts.googleapis.com/css2?display=swap&amp;family=Source%20Sans%20Pro&amp;family=Source%20Serif%20Pro"
    ]
    page.stylesheets = [
        "/css/apt-enjin.css"
    ]

[semantic.style]
    page.heading.font-family = "'Source Sans Pro', sans-serif"
    page.content.font-family = "'Source Serif Pro', serif"
    page.monospace.font-family = "monospace"
    page.dropcap.font-family = "'Source Sans Pro', sans-serif"
    color.working = "#a80030"

#:
#: Style Themes
#:

# --theme--instructions--*
[semantic.style.theme.instructions]
    fg = "var(--primary--fg)"
    bg = "var(--primary--bg)"
    accent.fg = "var(--secondary--fg)"
    accent.bg = "var(--secondary--bg)"
    highlight.fg = "var(--highlight--fg)"
    highlight.bg = "var(--highlight--bg)"
    alternate.fg = "var(--alternate--fg)"
    alternate.bg = "var(--alternate--bg)"
    overlay.dark.fg = "var(--overlay--dark--fg)"
    overlay.dark.bg = "var(--overlay--dark--bg)"
    overlay.light.fg = "var(--overlay--light--fg)"
    overlay.light.bg = "var(--overlay--light--bg)"
    border = "5px solid var(--theme--active--overlay--light--bg)"

#:
#: Block Themes (data-block-theme)
#:

# [data-block-theme="instructions"] { --style--* }
[semantic.block.theme.instructions]
    fg = "var(--theme--instructions--fg)"
    bg = "var(--theme--instructions--bg)"
    border = "var(--theme--instructions--border)"
    accent.fg = "var(--theme--instructions--accent--fg)"
    accent.bg = "var(--theme--instructions--accent--bg)"
    highlight.fg = "var(--theme--instructions--highlight--fg)"
    highlight.bg = "var(--theme--instructions--highlight--bg)"
    alternate.fg = "var(--theme--instructions--alternate--fg)"
    alternate.bg = "var(--theme--instructions--alternate--bg)"
    overlay.light.fg = "var(--theme--instructions--overlay--light--fg)"
    overlay.light.bg = "var(--theme--instructions--overlay--light--bg)"
    overlay.dark.fg = "var(--theme--instructions--overlay--dark--fg)"
    overlay.dark.bg = "var(--theme--instructions--overlay--dark--bg)"